export default {
  "class-methods-use-this": ["off"],
  "consistent-return": ["off"],
  "default-param-last": ["off"],
  "dot-notation": ["off"],
  "init-declarations": ["off"],
  "max-params": ["off"],
  "no-array-constructor": ["off"],
  "no-dupe-class-members": ["off"],
  "no-empty-function": ["off"],
  "no-invalid-this": ["off"],
  "no-loop-func": ["off"],
  "no-loss-of-precision": ["off"],
  "no-redeclare": ["off"],
  "no-restricted-imports": ["off"],
  "no-shadow": ["off"],
  "no-unused-expressions": ["off"],
  "no-unused-vars": ["off"],
  "no-use-before-define": ["off"],
  "no-useless-constructor": ["off"],
  "prefer-destructuring": ["off"],
  "prefer-promise-reject-errors": ["off"],
  "require-await": ["off"],
  "no-return-await": ["off"],

  "@typescript-eslint/adjacent-overload-signatures": ["error"],
  "@typescript-eslint/array-type": ["error", { "default": "array-simple" }],
  "@typescript-eslint/await-thenable": ["off"],
  "@typescript-eslint/ban-ts-comment": ["error"],
  "@typescript-eslint/ban-tslint-comment": ["error"],
  "@typescript-eslint/ban-types": ["error"],
  "@typescript-eslint/class-literal-property-style": ["error"],
  "@typescript-eslint/class-methods-use-this": ["off"],
  "@typescript-eslint/consistent-generic-constructors": ["error", "type-annotation"],
  "@typescript-eslint/consistent-indexed-object-style": ["error", "record"],
  "@typescript-eslint/consistent-return": ["off"],
  "@typescript-eslint/consistent-type-assertions": ["off"],
  "@typescript-eslint/consistent-type-definitions": ["off"],
  "@typescript-eslint/consistent-type-exports": ["off"],
  "@typescript-eslint/consistent-type-imports": ["off"],
  "@typescript-eslint/default-param-last": ["off"],
  "@typescript-eslint/dot-notation": ["off"],
  "@typescript-eslint/explicit-function-return-type": ["off"],
  "@typescript-eslint/explicit-member-accessibility": ["error"],
  "@typescript-eslint/explicit-module-boundary-types": ["off"],
  "@typescript-eslint/init-declarations": ["off"],
  "@typescript-eslint/max-params": ["off"],
  "@typescript-eslint/member-ordering": ["error"],
  "@typescript-eslint/method-signature-style": ["error", "method"],
  "@typescript-eslint/naming-convention": ["off"],
  "@typescript-eslint/no-array-constructor": ["error"],
  "@typescript-eslint/no-array-constructor": ["error"],
  "@typescript-eslint/no-array-delete": ["off"],
  "@typescript-eslint/no-base-to-string": ["off"],
  "@typescript-eslint/no-confusing-non-null-assertion": ["error"],
  "@typescript-eslint/no-confusing-void-expression": ["off"],
  "@typescript-eslint/no-dupe-class-members": ["error"],
  "@typescript-eslint/no-duplicate-enum-values": ["error"],
  "@typescript-eslint/no-duplicate-type-constituents": ["off"],
  "@typescript-eslint/no-dynamic-delete": ["off"],
  "@typescript-eslint/no-empty-function": ["off"],
  "@typescript-eslint/no-empty-interface": ["off"],
  "@typescript-eslint/no-empty-object-type": ["error"],
  "@typescript-eslint/no-explicit-any": ["error"],
  "@typescript-eslint/no-extra-non-null-assertion": ["error"],
  "@typescript-eslint/no-extraneous-class": ["error"],
  "@typescript-eslint/no-floating-promises": ["off"],
  "@typescript-eslint/no-for-in-array": ["off"],
  "@typescript-eslint/no-implied-eval": ["off"],
  "@typescript-eslint/no-import-type-side-effects": ["error"],
  "@typescript-eslint/no-inferrable-types": ["off"],
  "@typescript-eslint/no-invalid-this": ["off"],
  "@typescript-eslint/no-invalid-void-type": ["error"],
  "@typescript-eslint/no-loop-func": ["error"],
  "@typescript-eslint/no-loss-of-precision": ["error"],
  "@typescript-eslint/no-magic-numbers": ["off"],
  "@typescript-eslint/no-meaningless-void-operator": ["off"],
  "@typescript-eslint/no-misused-new": ["error"],
  "@typescript-eslint/no-misused-promises": ["off"],
  "@typescript-eslint/no-mixed-enums": ["off"],
  "@typescript-eslint/no-namespace": ["error"],
  "@typescript-eslint/no-non-null-asserted-nullish-coalescing": ["error"],
  "@typescript-eslint/no-non-null-asserted-optional-chain": ["error"],
  "@typescript-eslint/no-non-null-assertion": ["off"],
  "@typescript-eslint/no-redeclare": ["off"],
  "@typescript-eslint/no-redundant-type-constituents": ["off"],
  "@typescript-eslint/no-require-imports": ["error"],
  "@typescript-eslint/no-restricted-imports": ["error"],
  "@typescript-eslint/no-shadow": ["off"],
  "@typescript-eslint/no-this-alias": ["error"],
  "@typescript-eslint/no-unnecessary-boolean-literal-compare": ["off"],
  "@typescript-eslint/no-unnecessary-condition": ["off"],
  "@typescript-eslint/no-unnecessary-parameter-property-assignment": ["error"],
  "@typescript-eslint/no-unnecessary-qualifier": ["off"],
  "@typescript-eslint/no-unnecessary-template-expression": ["off"],
  "@typescript-eslint/no-unnecessary-type-arguments": ["off"],
  "@typescript-eslint/no-unnecessary-type-assertion": ["off"],
  "@typescript-eslint/no-unnecessary-type-constraint": ["error"],
  "@typescript-eslint/no-unnecessary-type-parameters": ["off"],
  "@typescript-eslint/no-unsafe-argument": ["off"],
  "@typescript-eslint/no-unsafe-assignment": ["off"],
  "@typescript-eslint/no-unsafe-call": ["off"],
  "@typescript-eslint/no-unsafe-declaration-merging": ["error"],
  "@typescript-eslint/no-unsafe-enum-comparison": ["off"],
  "@typescript-eslint/no-unsafe-member-access": ["off"],
  "@typescript-eslint/no-unsafe-return": ["off"],
  "@typescript-eslint/no-unsafe-unary-minus": ["off"],
  "@typescript-eslint/no-unused-expressions": ["error"],
  "@typescript-eslint/no-unused-vars": ["error"],
  "@typescript-eslint/no-use-before-define": ["off"],
  "@typescript-eslint/no-useless-constructor": ["error"],
  "@typescript-eslint/no-useless-empty-export": ["error"],
  "@typescript-eslint/no-var-requires": ["error"],
  "@typescript-eslint/non-nullable-type-assertion-style": ["off"],
  "@typescript-eslint/only-throw-error": ["off"],
  "@typescript-eslint/parameter-properties": ["error"],
  "@typescript-eslint/prefer-as-const": ["error"],
  "@typescript-eslint/prefer-destructuring": ["off"],
  "@typescript-eslint/prefer-enum-initializers": ["error"],
  "@typescript-eslint/prefer-find": ["off"],
  "@typescript-eslint/prefer-for-of": ["error"],
  "@typescript-eslint/prefer-function-type": ["error"],
  "@typescript-eslint/prefer-includes": ["off"],
  "@typescript-eslint/prefer-literal-enum-member": ["error"],
  "@typescript-eslint/prefer-namespace-keyword": ["off"],
  "@typescript-eslint/prefer-nullish-coalescing": ["off"],
  "@typescript-eslint/prefer-optional-chain": ["off"],
  "@typescript-eslint/prefer-promise-reject-errors": ["off"],
  "@typescript-eslint/prefer-readonly": ["off"],
  "@typescript-eslint/prefer-readonly-parameter-types": ["off"],
  "@typescript-eslint/prefer-reduce-type-parameter": ["off"],
  "@typescript-eslint/prefer-regexp-exec": ["off"],
  "@typescript-eslint/prefer-return-this-type": ["off"],
  "@typescript-eslint/prefer-string-starts-ends-with": ["off"],
  "@typescript-eslint/promise-function-async": ["off"],
  "@typescript-eslint/require-array-sort-compare": ["off"],
  "@typescript-eslint/require-await": ["off"],
  "@typescript-eslint/restrict-plus-operands": ["off"],
  "@typescript-eslint/restrict-template-expressions": ["off"],
  "@typescript-eslint/return-await": ["off"],
  "@typescript-eslint/strict-boolean-expressions": ["off"],
  "@typescript-eslint/switch-exhaustiveness-check": ["off"],
  "@typescript-eslint/triple-slash-reference": ["off"],
  "@typescript-eslint/typedef": ["off"],
  "@typescript-eslint/unbound-method": ["off"],
  "@typescript-eslint/unified-signatures": ["off"],
  "@typescript-eslint/use-unknown-in-catch-callback-variable": ["off"],

  "@stylistic/array-bracket-newline": ["error", "consistent"],
  "@stylistic/array-bracket-spacing": ["error", "never"],
  "@stylistic/array-element-newline": ["error", "consistent"],
  "@stylistic/arrow-parens": ["error", "always"],
  "@stylistic/arrow-spacing": ["error", { "before": true, "after": true }],
  "@stylistic/block-spacing": ["error", "always"],
  "@stylistic/brace-style": ["error", "1tbs"],
  "@stylistic/comma-dangle": ["error", "always-multiline"],
  "@stylistic/comma-spacing": ["error", { "before": false, "after": true }],
  "@stylistic/comma-style": ["error", "last"],
  "@stylistic/computed-property-spacing": ["error", "never"],
  "@stylistic/dot-location": ["error", "property"],
  "@stylistic/eol-last": ["error", "always"],
  "@stylistic/function-call-argument-newline": ["error", "consistent"],
  "@stylistic/function-call-spacing": ["error", "never"],
  "@stylistic/function-paren-newline": ["error", "consistent"],
  "@stylistic/generator-star-spacing": ["error", { "before": true, "after": false }],
  "@stylistic/implicit-arrow-linebreak": ["off"],
  "@stylistic/indent": ["error", 2],
  "@stylistic/indent-binary-ops": ["error", 2],
  "@stylistic/key-spacing": ["error", { "beforeColon": false, "afterColon": true, "mode": "strict" }],
  "@stylistic/keyword-spacing": ["error", { "before": true, "after": true }],
  "@stylistic/linebreak-style": ["error", "unix"],
  "@stylistic/lines-around-comment": ["error", {
    "beforeBlockComment": true,
    "afterBlockComment": false,
    "beforeLineComment": true,
    "afterLineComment": false,
    "allowBlockStart": true,
    "allowClassStart": false,
    "allowObjectStart": true,
    "allowArrayStart": true,
  }],
  "@stylistic/lines-between-class-members": ["off"],
  "@stylistic/max-len": ["error", {
    "code": 120,
    "comments": 120,
    "ignoreUrls": true,
    "ignoreStrings": true,
    "ignoreTemplateLiterals": true,
    "ignoreRegExpLiterals": true,
  }],
  "@stylistic/max-statements-per-line": ["off"],
  "@stylistic/member-delimiter-style": ["error", {
    "multiline": {
      "delimiter": "semi",
      "requireLast": true,
    },
    "singleline": {
      "delimiter": "semi",
      "requireLast": false,
    },
    "multilineDetection": "brackets",
  }],
  "@stylistic/multiline-ternary": ["error", "always-multiline"],
  "@stylistic/new-parens": ["error", "always"],
  "@stylistic/newline-per-chained-call": ["off"],
  "@stylistic/no-confusing-arrow": ["error"],
  "@stylistic/no-extra-parens": ["off"],
  "@stylistic/no-extra-semi": ["error"],
  "@stylistic/no-floating-decimal": ["error"],
  "@stylistic/no-mixed-operators": ["off"],
  "@stylistic/no-mixed-spaces-and-tabs": ["error"],
  "@stylistic/no-multi-spaces": ["error"],
  "@stylistic/no-multiple-empty-lines": ["error", { "max": 1 }],
  "@stylistic/no-tabs": ["error"],
  "@stylistic/no-trailing-spaces": ["error"],
  "@stylistic/no-whitespace-before-property": ["error"],
  "@stylistic/nonblock-statement-body-position": ["error", "beside"],
  "@stylistic/object-curly-newline": ["error", { "consistent": true }],
  "@stylistic/object-curly-spacing": ["error", "always"],
  "@stylistic/object-property-newline": ["off"],
  "@stylistic/one-var-declaration-per-line": ["error", "always"],
  "@stylistic/operator-linebreak": ["error", "before"],
  "@stylistic/padded-blocks": ["error", "never"],
  "@stylistic/padding-line-between-statements": ["off"],
  "@stylistic/quote-props": ["error", "consistent"],
  "@stylistic/quotes": ["error", "double"],
  "@stylistic/rest-spread-spacing": ["error", "never"],
  "@stylistic/semi": ["error", "always", { omitLastInOneLineBlock: true }],
  "@stylistic/semi-spacing": ["error", { "before": false, "after": true }],
  "@stylistic/semi-style": ["off"],
  "@stylistic/space-before-blocks": ["error", "always"],
  "@stylistic/space-before-function-paren": ["error", {
    "anonymous": "always",
    "asyncArrow": "always",
    "named": "never",
  }],
  "@stylistic/space-in-parens": ["error", "never"],
  "@stylistic/space-infix-ops": ["error"],
  "@stylistic/space-unary-ops": ["error", { "words": true, "nonwords": false }],
  "@stylistic/spaced-comment": ["error", "always"],
  "@stylistic/switch-colon-spacing": ["error", { "before": false, "after": true }],
  "@stylistic/template-curly-spacing": ["error", "never"],
  "@stylistic/template-tag-spacing": ["error", "never"],
  "@stylistic/type-annotation-spacing": ["error", { "before": false, "after": true }],
  "@stylistic/type-generic-spacing": ["error"],
  "@stylistic/type-named-tuple-spacing": ["error"],
  "@stylistic/wrap-iife": ["error", "inside"],
  "@stylistic/wrap-regex": ["off"],
  "@stylistic/yield-star-spacing": ["error", { "before": false, "after": true }],
}