export default {
  "@stylistic/array-bracket-newline": ["error", "consistent"],
  "@stylistic/array-bracket-spacing": ["error", "never"],
  "@stylistic/array-element-newline": ["error", "consistent"],
  "@stylistic/arrow-parens": ["error", "always"],
  "@stylistic/arrow-spacing": ["error", { "before": true, "after": true }],
  "@stylistic/block-spacing": ["error", "always"],
  "@stylistic/brace-style": ["error", "1tbs"],
  "@stylistic/comma-dangle": ["error", "always-multiline"],
  "@stylistic/comma-spacing": ["error", { "before": false, "after": true }],
  "@stylistic/comma-style": ["error", "last"],
  "@stylistic/computed-property-spacing": ["error", "never"],
  "@stylistic/dot-location": ["error", "property"],
  "@stylistic/eol-last": ["error", "always"],
  "@stylistic/function-call-argument-newline": ["error", "consistent"],
  "@stylistic/function-call-spacing": ["error", "never"],
  "@stylistic/function-paren-newline": ["error", "consistent"],
  "@stylistic/generator-star-spacing": ["error", { "before": true, "after": false }],
  "@stylistic/implicit-arrow-linebreak": ["off"],
  "@stylistic/indent": ["error", 2],
  "@stylistic/indent-binary-ops": ["error", 2],
  "@stylistic/key-spacing": ["error", { "beforeColon": false, "afterColon": true, "mode": "strict" }],
  "@stylistic/keyword-spacing": ["error", { "before": true, "after": true }],
  "@stylistic/linebreak-style": ["error", "unix"],
  "@stylistic/lines-around-comment": ["error", {
    "beforeBlockComment": true,
    "afterBlockComment": false,
    "beforeLineComment": true,
    "afterLineComment": false,
    "allowBlockStart": true,
    "allowClassStart": false,
    "allowObjectStart": true,
    "allowArrayStart": true,
  }],
  "@stylistic/lines-between-class-members": ["off"],
  "@stylistic/max-len": ["error", {
    "code": 120,
    "comments": 120,
    "ignoreUrls": true,
    "ignoreStrings": true,
    "ignoreTemplateLiterals": true,
    "ignoreRegExpLiterals": true,
  }],
  "@stylistic/max-statements-per-line": ["off"],
  "@stylistic/member-delimiter-style": ["error", {
    "multiline": {
      "delimiter": "semi",
      "requireLast": true,
    },
    "singleline": {
      "delimiter": "semi",
      "requireLast": false,
    },
    "multilineDetection": "brackets",
  }],
  "@stylistic/multiline-ternary": ["error", "always-multiline"],
  "@stylistic/new-parens": ["error", "always"],
  "@stylistic/newline-per-chained-call": ["off"],
  "@stylistic/no-confusing-arrow": ["error"],
  "@stylistic/no-extra-parens": ["off"],
  "@stylistic/no-extra-semi": ["error"],
  "@stylistic/no-floating-decimal": ["error"],
  "@stylistic/no-mixed-operators": ["off"],
  "@stylistic/no-mixed-spaces-and-tabs": ["error"],
  "@stylistic/no-multi-spaces": ["error"],
  "@stylistic/no-multiple-empty-lines": ["error", { "max": 1 }],
  "@stylistic/no-tabs": ["error"],
  "@stylistic/no-trailing-spaces": ["error"],
  "@stylistic/no-whitespace-before-property": ["error"],
  "@stylistic/nonblock-statement-body-position": ["error", "beside"],
  "@stylistic/object-curly-newline": ["error", { "consistent": true }],
  "@stylistic/object-curly-spacing": ["error", "always"],
  "@stylistic/object-property-newline": ["off"],
  "@stylistic/one-var-declaration-per-line": ["error", "always"],
  "@stylistic/operator-linebreak": ["error", "before"],
  "@stylistic/padded-blocks": ["error", "never"],
  "@stylistic/padding-line-between-statements": ["off"],
  "@stylistic/quote-props": ["error", "consistent"],
  "@stylistic/quotes": ["error", "double"],
  "@stylistic/rest-spread-spacing": ["error", "never"],
  "@stylistic/semi": ["error", "always", { omitLastInOneLineBlock: true }],
  "@stylistic/semi-spacing": ["error", { "before": false, "after": true }],
  "@stylistic/semi-style": ["off"],
  "@stylistic/space-before-blocks": ["error", "always"],
  "@stylistic/space-before-function-paren": ["error", {
    "anonymous": "always",
    "asyncArrow": "always",
    "named": "never",
  }],
  "@stylistic/space-in-parens": ["error", "never"],
  "@stylistic/space-infix-ops": ["error"],
  "@stylistic/space-unary-ops": ["error", { "words": true, "nonwords": false }],
  "@stylistic/spaced-comment": ["error", "always"],
  "@stylistic/switch-colon-spacing": ["error", { "before": false, "after": true }],
  "@stylistic/template-curly-spacing": ["error", "never"],
  "@stylistic/template-tag-spacing": ["error", "never"],
  "@stylistic/type-annotation-spacing": ["error", { "before": false, "after": true }],
  "@stylistic/type-generic-spacing": ["error"],
  "@stylistic/type-named-tuple-spacing": ["error"],
  "@stylistic/wrap-iife": ["error", "inside"],
  "@stylistic/wrap-regex": ["off"],
  "@stylistic/yield-star-spacing": ["error", { "before": false, "after": true }],
}